## Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/nisum?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username : root
    password: root
  jpa:
   properties:
    hibernate:
     dialect : org.hibernate.dialect.MySQL5InnoDBDialect
     ddl-auto: none
   show-sql: true

server:
  port: 8081